# Generated by Django 4.2 on 2026-07-18 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_post_reported_by_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postattachment',
            name='nsfw_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
